name: Development - Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  development:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Clean cache and install dependencies
        run: |
          npm cache clean --force
          rm -f package-lock.json
          npm ci

      - name: Build
        run: npm run build
        env:
          CI: false

  deploy:
    needs: development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install FTP-Deploy-Action
        run: npm install -g SamKirkland/FTP-Deploy-Action

      - name: FTP Deploy
        run: ftp-deploy
        with:
          server: ftp.nl1-ss105.a2hosting.com
          username: servi151
          password: ${{ secrets.SERVER_SECRET }}
          server-dir: api.servicexpress.biz/
