name: Development - Build and Deploy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: echo Hello World
      - name: upload
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.nl1-ss105.a2hosting.com
          username: servi151
          password: ${{ secrets.SERVER_SECRET }}
          server-dir: api.servicexpress.biz/
